export const LOAD_RECIPES_SUCCESS = "LOAD_RECIPES_SUCCESS";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const FILTER_RECIPES = "FILTER_RECIPES";
